-- database
DROP DATABASE IF EXISTS jag;
CREATE DATABASE jag;

-- user
DROP USER IF EXISTS jag;
CREATE USER jag WITH PASSWORD 'Q91Gaj';

-- privileges
GRANT ALL PRIVILEGES ON DATABASE jag TO jag;
GRANT USAGE ON SCHEMA workshop TO jag;
ALTER USER jag WITH SUPERUSER;